# Generated by Django 5.2.7 on 2025-10-26 17:35

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="what_do_you_like",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("sports", "Sports"),
                    ("music", "Music"),
                    ("reading", "Reading"),
                    ("game", "Games"),
                    ("technology", "Technology"),
                    ("movies", "Movies"),
                    ("languages", "Languages"),
                    ("fashion", "Fashion"),
                ],
                max_length=61,
            ),
        ),
    ]
